"""BADGERxADVENTURES listings app.

Flask + SQLite. Public map shows every pin. A code, generated by the admin,
is the only way to create an owner account, and each code is good for
exactly one pin. Once placed, an owner can keep editing (but never delete)
their own pin's photos/phone/description/events/availability; only the
admin can edit or delete any pin.
"""
import json
import os
import uuid
from functools import wraps

from flask import Flask, request, jsonify, render_template, g, send_from_directory
from PIL import Image, ImageOps

import db
import auth

app = Flask(__name__)
UPLOAD_DIR = os.path.join(os.path.dirname(__file__), "static", "uploads")
os.makedirs(UPLOAD_DIR, exist_ok=True)
MAX_PHOTOS = 8
MAX_UPLOAD_BYTES = 12 * 1024 * 1024  # 12MB raw upload cap per file, before we resize down

# Run once at import time (not just under `python app.py`) so this also fires
# under a production WSGI server like gunicorn, which imports `app:app` directly
# and never executes the __main__ block below.
db.init_db()


# ---------- request helpers ----------

def get_db():
    if "db" not in g:
        g.db = db.get_db()
    return g.db


@app.teardown_appcontext
def close_db(exc):
    d = g.pop("db", None)
    if d is not None:
        d.close()


def current_owner_id():
    token = request.cookies.get("owner_session")
    if not token:
        return None
    return auth.read_owner_token(token)


def current_admin_id():
    token = request.cookies.get("admin_session")
    if not token:
        return None
    return auth.read_admin_token(token)


def owner_required(fn):
    @wraps(fn)
    def wrapper(*a, **kw):
        oid = current_owner_id()
        if not oid:
            return jsonify({"error": "not logged in"}), 401
        g.owner_id = oid
        return fn(*a, **kw)
    return wrapper


def admin_required(fn):
    @wraps(fn)
    def wrapper(*a, **kw):
        aid = current_admin_id()
        if not aid:
            return jsonify({"error": "admin login required"}), 401
        g.admin_id = aid
        return fn(*a, **kw)
    return wrapper


def pin_to_json(row):
    d = dict(row)
    d["photos"] = json.loads(d.get("photos") or "[]")
    d["availability"] = json.loads(d.get("availability") or "[]")
    return d


# ---------- public pages ----------

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/redeem")
def redeem_page():
    return render_template("redeem.html")


@app.route("/login")
def login_page():
    return render_template("login.html")


@app.route("/dashboard")
def dashboard_page():
    return render_template("dashboard.html")


@app.route("/admin/login")
def admin_login_page():
    return render_template("admin_login.html")


@app.route("/admin")
def admin_page():
    return render_template("admin.html")


@app.route("/static/uploads/<path:name>")
def uploaded_file(name):
    return send_from_directory(UPLOAD_DIR, name)


# ---------- public API ----------

@app.route("/api/pins")
def api_pins():
    rows = get_db().execute(
        "SELECT id, pin_type, title, description, phone, address, lat, lon, "
        "photos, events, availability FROM pins ORDER BY id"
    ).fetchall()
    return jsonify([pin_to_json(r) for r in rows])


# ---------- code redemption + owner auth ----------

@app.route("/api/redeem", methods=["POST"])
def api_redeem():
    data = request.get_json(force=True) or {}
    code = (data.get("code") or "").strip().upper()
    email = (data.get("email") or "").strip().lower()
    password = data.get("password") or ""
    if not code or not email or len(password) < 8:
        return jsonify({"error": "Enter your code, an email, and a password (8+ characters)."}), 400

    conn = get_db()
    row = conn.execute("SELECT * FROM invite_codes WHERE code = ?", (code,)).fetchone()
    if not row:
        return jsonify({"error": "That code isn't recognized."}), 404
    if row["status"] != "unused":
        return jsonify({"error": "That code has already been used."}), 409
    if conn.execute("SELECT 1 FROM owners WHERE email = ?", (email,)).fetchone():
        return jsonify({"error": "That email already has an account."}), 409

    pw_hash = auth.hash_password(password)
    cur = conn.execute(
        "INSERT INTO owners (code_id, email, password_hash) VALUES (?, ?, ?)",
        (row["id"], email, pw_hash),
    )
    owner_id = cur.lastrowid
    conn.execute(
        "UPDATE invite_codes SET status = 'claimed', claimed_at = datetime('now') WHERE id = ?",
        (row["id"],),
    )
    conn.commit()

    resp = jsonify({"ok": True, "pin_type": row["pin_type"]})
    token = auth.make_owner_token(owner_id)
    resp.set_cookie("owner_session", token, httponly=True, samesite="Lax", max_age=60 * 60 * 24 * 30)
    return resp


@app.route("/api/login", methods=["POST"])
def api_login():
    data = request.get_json(force=True) or {}
    email = (data.get("email") or "").strip().lower()
    password = data.get("password") or ""
    conn = get_db()
    row = conn.execute("SELECT * FROM owners WHERE email = ?", (email,)).fetchone()
    if not row or not auth.verify_password(password, row["password_hash"]):
        return jsonify({"error": "Wrong email or password."}), 401
    resp = jsonify({"ok": True})
    token = auth.make_owner_token(row["id"])
    resp.set_cookie("owner_session", token, httponly=True, samesite="Lax", max_age=60 * 60 * 24 * 30)
    return resp


@app.route("/api/logout", methods=["POST"])
def api_logout():
    resp = jsonify({"ok": True})
    resp.delete_cookie("owner_session")
    return resp


# ---------- owner: their own pin only ----------

@app.route("/api/my-pin", methods=["GET"])
@owner_required
def api_my_pin_get():
    conn = get_db()
    owner = conn.execute("SELECT o.*, c.pin_type AS code_pin_type FROM owners o "
                          "JOIN invite_codes c ON c.id = o.code_id WHERE o.id = ?",
                          (g.owner_id,)).fetchone()
    pin = conn.execute("SELECT * FROM pins WHERE owner_id = ?", (g.owner_id,)).fetchone()
    return jsonify({
        "email": owner["email"],
        "allowed_pin_type": owner["code_pin_type"],
        "pin": pin_to_json(pin) if pin else None,
    })


@app.route("/api/my-pin", methods=["POST"])
@owner_required
def api_my_pin_create():
    """Place the owner's one and only pin. Fails if they already have one."""
    conn = get_db()
    existing = conn.execute("SELECT 1 FROM pins WHERE owner_id = ?", (g.owner_id,)).fetchone()
    if existing:
        return jsonify({"error": "You've already placed your pin. Edit it instead."}), 409

    owner = conn.execute("SELECT c.pin_type FROM owners o JOIN invite_codes c ON c.id = o.code_id "
                          "WHERE o.id = ?", (g.owner_id,)).fetchone()
    data = request.get_json(force=True) or {}
    lat, lon = data.get("lat"), data.get("lon")
    title = (data.get("title") or "").strip()
    if lat is None or lon is None or not title:
        return jsonify({"error": "A location on the map and a name are required."}), 400
    if not (36.55 <= float(lat) <= 37.25 and -85.4 <= float(lon) <= -84.3):
        return jsonify({"error": "That location is outside the Lake Cumberland map."}), 400

    conn.execute(
        "INSERT INTO pins (owner_id, pin_type, title, description, phone, address, lat, lon, events) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (g.owner_id, owner["pin_type"], title, data.get("description", ""), data.get("phone", ""),
         data.get("address", ""), float(lat), float(lon), data.get("events", "")),
    )
    conn.commit()
    return jsonify({"ok": True})


@app.route("/api/my-pin", methods=["PUT"])
@owner_required
def api_my_pin_update():
    conn = get_db()
    pin = conn.execute("SELECT * FROM pins WHERE owner_id = ?", (g.owner_id,)).fetchone()
    if not pin:
        return jsonify({"error": "Place your pin first."}), 404
    data = request.get_json(force=True) or {}
    fields = {}
    for key in ("title", "description", "phone", "address", "events"):
        if key in data:
            fields[key] = str(data[key])
    if "availability" in data:
        avail = data["availability"]
        if not isinstance(avail, list):
            return jsonify({"error": "Bad availability data."}), 400
        fields["availability"] = json.dumps(avail)
    if not fields:
        return jsonify({"error": "Nothing to update."}), 400
    set_clause = ", ".join(f"{k} = ?" for k in fields)
    conn.execute(f"UPDATE pins SET {set_clause}, updated_at = datetime('now') WHERE owner_id = ?",
                 (*fields.values(), g.owner_id))
    conn.commit()
    return jsonify({"ok": True})


def _save_photo(file_storage):
    img = Image.open(file_storage.stream)
    img = ImageOps.exif_transpose(img)  # respect phone camera orientation, then drop the EXIF
    img = img.convert("RGB")
    img.thumbnail((1600, 1600))
    name = f"{uuid.uuid4().hex}.jpg"
    img.save(os.path.join(UPLOAD_DIR, name), "JPEG", quality=82)
    return f"/static/uploads/{name}"


@app.route("/api/my-pin/photos", methods=["POST"])
@owner_required
def api_my_pin_add_photo():
    conn = get_db()
    pin = conn.execute("SELECT * FROM pins WHERE owner_id = ?", (g.owner_id,)).fetchone()
    if not pin:
        return jsonify({"error": "Place your pin first."}), 404
    photos = json.loads(pin["photos"] or "[]")
    if len(photos) >= MAX_PHOTOS:
        return jsonify({"error": f"Max {MAX_PHOTOS} photos."}), 400
    file = request.files.get("photo")
    if not file or not file.content_type.startswith("image/"):
        return jsonify({"error": "Please upload an image file."}), 400
    try:
        path = _save_photo(file)
    except Exception:
        return jsonify({"error": "Couldn't read that image."}), 400
    photos.append(path)
    conn.execute("UPDATE pins SET photos = ?, updated_at = datetime('now') WHERE owner_id = ?",
                 (json.dumps(photos), g.owner_id))
    conn.commit()
    return jsonify({"ok": True, "photos": photos})


@app.route("/api/my-pin/photos", methods=["DELETE"])
@owner_required
def api_my_pin_remove_photo():
    conn = get_db()
    pin = conn.execute("SELECT * FROM pins WHERE owner_id = ?", (g.owner_id,)).fetchone()
    if not pin:
        return jsonify({"error": "Place your pin first."}), 404
    data = request.get_json(force=True) or {}
    path = data.get("path")
    photos = json.loads(pin["photos"] or "[]")
    if path not in photos:
        return jsonify({"error": "Photo not found."}), 404
    photos.remove(path)
    conn.execute("UPDATE pins SET photos = ?, updated_at = datetime('now') WHERE owner_id = ?",
                 (json.dumps(photos), g.owner_id))
    conn.commit()
    fname = os.path.basename(path)
    fpath = os.path.join(UPLOAD_DIR, fname)
    if os.path.exists(fpath):
        os.remove(fpath)
    return jsonify({"ok": True, "photos": photos})


# ---------- admin ----------

@app.route("/api/admin/login", methods=["POST"])
def api_admin_login():
    data = request.get_json(force=True) or {}
    email = (data.get("email") or "").strip().lower()
    password = data.get("password") or ""
    conn = get_db()
    row = conn.execute("SELECT * FROM admins WHERE email = ?", (email,)).fetchone()
    if not row or not auth.verify_password(password, row["password_hash"]):
        return jsonify({"error": "Wrong email or password."}), 401
    resp = jsonify({"ok": True})
    token = auth.make_admin_token(row["id"])
    resp.set_cookie("admin_session", token, httponly=True, samesite="Lax", max_age=60 * 60 * 24 * 30)
    return resp


@app.route("/api/admin/logout", methods=["POST"])
def api_admin_logout():
    resp = jsonify({"ok": True})
    resp.delete_cookie("admin_session")
    return resp


@app.route("/api/admin/codes", methods=["GET"])
@admin_required
def api_admin_codes_list():
    rows = get_db().execute(
        "SELECT ic.*, o.email AS claimed_by_email FROM invite_codes ic "
        "LEFT JOIN owners o ON o.code_id = ic.id ORDER BY ic.id DESC"
    ).fetchall()
    return jsonify([dict(r) for r in rows])


@app.route("/api/admin/codes", methods=["POST"])
@admin_required
def api_admin_codes_create():
    data = request.get_json(force=True) or {}
    pin_type = data.get("pin_type")
    if pin_type not in ("business", "stay", "custom"):
        return jsonify({"error": "pin_type must be business, stay, or custom."}), 400
    code = auth.gen_invite_code()
    conn = get_db()
    conn.execute("INSERT INTO invite_codes (code, pin_type, label) VALUES (?, ?, ?)",
                 (code, pin_type, data.get("label", "")))
    conn.commit()
    return jsonify({"ok": True, "code": code})


@app.route("/api/admin/codes/<int:code_id>", methods=["DELETE"])
@admin_required
def api_admin_codes_delete(code_id):
    conn = get_db()
    row = conn.execute("SELECT * FROM invite_codes WHERE id = ?", (code_id,)).fetchone()
    if not row:
        return jsonify({"error": "Not found."}), 404
    if row["status"] == "claimed":
        return jsonify({"error": "Can't delete a code that's already been used — delete the owner instead."}), 409
    conn.execute("DELETE FROM invite_codes WHERE id = ?", (code_id,))
    conn.commit()
    return jsonify({"ok": True})


@app.route("/api/admin/pins", methods=["GET"])
@admin_required
def api_admin_pins_list():
    rows = get_db().execute(
        "SELECT p.*, o.email AS owner_email FROM pins p LEFT JOIN owners o ON o.id = p.owner_id "
        "ORDER BY p.id"
    ).fetchall()
    return jsonify([pin_to_json(r) for r in rows])


@app.route("/api/admin/pins", methods=["POST"])
@admin_required
def api_admin_pins_create():
    """Admin can also drop a pin directly (e.g. a custom landmark) with no owner login."""
    data = request.get_json(force=True) or {}
    pin_type = data.get("pin_type")
    title = (data.get("title") or "").strip()
    lat, lon = data.get("lat"), data.get("lon")
    if pin_type not in ("business", "stay", "custom") or not title or lat is None or lon is None:
        return jsonify({"error": "pin_type, title, lat, and lon are required."}), 400
    conn = get_db()
    conn.execute(
        "INSERT INTO pins (owner_id, pin_type, title, description, phone, address, lat, lon, events) "
        "VALUES (NULL, ?, ?, ?, ?, ?, ?, ?, ?)",
        (pin_type, title, data.get("description", ""), data.get("phone", ""), data.get("address", ""),
         float(lat), float(lon), data.get("events", "")),
    )
    conn.commit()
    return jsonify({"ok": True})


@app.route("/api/admin/pins/<int:pin_id>", methods=["PUT"])
@admin_required
def api_admin_pins_update(pin_id):
    conn = get_db()
    pin = conn.execute("SELECT * FROM pins WHERE id = ?", (pin_id,)).fetchone()
    if not pin:
        return jsonify({"error": "Not found."}), 404
    data = request.get_json(force=True) or {}
    fields = {}
    for key in ("title", "description", "phone", "address", "events", "pin_type", "lat", "lon"):
        if key in data:
            fields[key] = data[key]
    if "availability" in data:
        fields["availability"] = json.dumps(data["availability"])
    if "photos" in data:
        fields["photos"] = json.dumps(data["photos"])
    if not fields:
        return jsonify({"error": "Nothing to update."}), 400
    set_clause = ", ".join(f"{k} = ?" for k in fields)
    conn.execute(f"UPDATE pins SET {set_clause}, updated_at = datetime('now') WHERE id = ?",
                 (*fields.values(), pin_id))
    conn.commit()
    return jsonify({"ok": True})


@app.route("/api/admin/pins/<int:pin_id>", methods=["DELETE"])
@admin_required
def api_admin_pins_delete(pin_id):
    conn = get_db()
    conn.execute("DELETE FROM pins WHERE id = ?", (pin_id,))
    conn.commit()
    return jsonify({"ok": True})


@app.route("/api/admin/owners/<int:owner_id>", methods=["DELETE"])
@admin_required
def api_admin_owners_delete(owner_id):
    """Fully revoke an owner: deletes their account and pin (FK cascade)."""
    conn = get_db()
    conn.execute("DELETE FROM owners WHERE id = ?", (owner_id,))
    conn.commit()
    return jsonify({"ok": True})


if __name__ == "__main__":
    # Local dev only. In production a WSGI server (gunicorn, per the Procfile)
    # runs `app:app` instead of this block, with debug off.
    port = int(os.environ.get("PORT", 5055))
    debug = os.environ.get("FLASK_DEBUG", "0") == "1"
    app.run(host="0.0.0.0", port=port, debug=debug)
