"""BADGERxADVENTURES listings app.

Flask + SQLite, serving the full themed Lake Cumberland map (illustrated
USGS-based shoreline, the badger jet-ski game, and a live NWS weather strip)
that was originally built as a Claude Artifact, now wired to a real backend.

A code, generated by the admin, is the only way to create an owner account,
and each code is good for exactly one pin (a business, a cabin/stay, or a
custom landmark pin). Once placed, an owner can keep editing their pin's
info and photos -- but never its location, which is set once, server-side,
and can only ever be moved again by an admin. Only the admin account can
edit or delete any pin, and only the admin can generate invite codes.
"""
import json
import os
import uuid
from datetime import datetime, timezone
from functools import wraps

from flask import Flask, request, jsonify, render_template, g, send_from_directory, redirect
from PIL import Image, ImageOps

import db
import auth
import weather

app = Flask(__name__)
_RENDER_DISK_DIR = "/opt/render/project/src/instance"
_DATA_DIR = _RENDER_DISK_DIR if os.path.isdir(_RENDER_DISK_DIR) else os.path.join(os.path.dirname(__file__), "instance")
UPLOAD_DIR = os.path.join(_DATA_DIR, "uploads")
os.makedirs(UPLOAD_DIR, exist_ok=True)
MAX_PHOTOS_BY_TYPE = {"business": 3, "custom": 3, "stay": 5}
MAX_UPLOAD_BYTES = 12 * 1024 * 1024  # 12MB raw upload cap per file, before we resize down

# Run once at import time (not just under `python app.py`) so this also fires
# under a production WSGI server like gunicorn, which imports `app:app` directly
# and never executes the __main__ block below.
db.init_db()


# ---------- request helpers ----------

def get_db():
    if "db" not in g:
        g.db = db.get_db()
    return g.db


@app.teardown_appcontext
def close_db(exc):
    d = g.pop("db", None)
    if d is not None:
        d.close()


def current_owner_id():
    token = request.cookies.get("owner_session")
    if not token:
        return None
    return auth.read_owner_token(token)


def current_admin_id():
    token = request.cookies.get("admin_session")
    if not token:
        return None
    return auth.read_admin_token(token)


def owner_required(fn):
    @wraps(fn)
    def wrapper(*a, **kw):
        oid = current_owner_id()
        if not oid:
            return jsonify({"error": "not logged in"}), 401
        g.owner_id = oid
        return fn(*a, **kw)
    return wrapper


def admin_required(fn):
    @wraps(fn)
    def wrapper(*a, **kw):
        aid = current_admin_id()
        if not aid:
            return jsonify({"error": "admin login required"}), 401
        g.admin_id = aid
        return fn(*a, **kw)
    return wrapper


def compute_role():
    """What the themed page (and the API) treats this visitor as: a browsing
    guest, a signed-in business/stay/pin owner, or the admin. Computed from
    the session cookies, never trusted from anything the client sends.
    """
    if current_admin_id():
        return {"kind": "admin", "ownerId": None, "pinType": None, "hasPin": False, "pinId": None}
    owner_id = current_owner_id()
    if owner_id:
        conn = get_db()
        owner = conn.execute(
            "SELECT o.id, c.pin_type AS code_pin_type FROM owners o "
            "JOIN invite_codes c ON c.id = o.code_id WHERE o.id = ?",
            (owner_id,),
        ).fetchone()
        if owner:
            pin = conn.execute("SELECT id FROM pins WHERE owner_id = ?", (owner_id,)).fetchone()
            return {
                "kind": "owner",
                "ownerId": owner_id,
                "pinType": owner["code_pin_type"],
                "hasPin": bool(pin),
                "pinId": pin["id"] if pin else None,
            }
    return {"kind": "guest", "ownerId": None, "pinType": None, "hasPin": False, "pinId": None}


def _to_ms(iso_str):
    if not iso_str:
        return None
    try:
        dt = datetime.strptime(iso_str, "%Y-%m-%d %H:%M:%S").replace(tzinfo=timezone.utc)
        return int(dt.timestamp() * 1000)
    except ValueError:
        return None


def row_to_client_doc(row):
    """A DB row -> the exact pin/stay document shape the ported front-end
    JS expects (see script.pretty.js's editPin/editStay/renderDetail). Returns
    (kind, doc) where kind is "pin" or "stay".
    """
    d = dict(row)
    photos = json.loads(d.get("photos") or "[]")
    thumb = photos[0] if photos else ""
    base = {
        "id": d["id"],
        "title": d.get("title") or "",
        "phone": d.get("phone") or "",
        "events": d.get("events") or "",
        "x": d["x"],
        "y": d["y"],
        "thumb": thumb,
        "photos": photos,
        "at": _to_ms(d.get("created_at")),
        "upd": _to_ms(d.get("updated_at")),
    }
    if d["pin_type"] == "stay":
        base["type"] = d.get("sub_type") or "cabin"
        base["desc"] = d.get("description") or ""
        base["address"] = d.get("address") or ""
        base["route"] = d.get("route") or ""
        base["host"] = d.get("host") or ""
        base["price"] = d.get("price")
        base["sleeps"] = d.get("sleeps")
        base["beds"] = d.get("beds")
        base["baths"] = d.get("baths")
        base["avail"] = json.loads(d.get("availability") or "[]")
        road_pts = json.loads(d.get("road_pts") or "[]")
        road_name = d.get("road_name") or ""
        if road_pts and road_name:
            base["road"] = {"name": road_name, "pts": road_pts}
        return "stay", base
    base["cat"] = d.get("sub_type") or "custom"
    base["desc"] = d.get("description") or ""
    base["hours"] = d.get("hours") or ""
    base["when"] = d.get("when_at") or ""
    base["menu"] = json.loads(d.get("menu") or "[]")
    return "pin", base


def fetch_docs():
    rows = get_db().execute("SELECT * FROM pins ORDER BY id").fetchall()
    pins, stays = [], []
    for r in rows:
        kind, doc = row_to_client_doc(r)
        (stays if kind == "stay" else pins).append(doc)
    return pins, stays


def business_fields_from_payload(data):
    """cat/title/description/events/hours/phone/when_at/menu -> DB columns.
    Used for both 'business' and 'custom' pins (a custom pin is just a
    business-shaped pin with an empty category)."""
    fields = {}
    if "cat" in data:
        fields["sub_type"] = str(data.get("cat") or "")[:40]
    for key in ("title", "description", "events", "hours", "phone"):
        if key in data:
            fields[key] = str(data.get(key) or "")
    if "when_at" in data:
        fields["when_at"] = str(data.get("when_at") or "")
    if "menu" in data:
        menu = data["menu"]
        if not isinstance(menu, list):
            raise ValueError("Bad menu data.")
        fields["menu"] = json.dumps(menu)
    return fields


def stay_fields_from_payload(data):
    fields = {}
    if "type" in data:
        fields["sub_type"] = str(data.get("type") or "")[:40]
    for key in ("title", "description", "events", "address", "route", "phone", "host"):
        if key in data:
            fields[key] = str(data.get(key) or "")
    for key in ("price", "sleeps", "beds"):
        if key in data:
            v = data[key]
            fields[key] = int(v) if v is not None else None
    if "baths" in data:
        v = data["baths"]
        fields["baths"] = float(v) if v is not None else None
    if "availability" in data:
        avail = data["availability"]
        if not isinstance(avail, list):
            raise ValueError("Bad availability data.")
        fields["availability"] = json.dumps(avail)
    if "road_name" in data:
        fields["road_name"] = str(data.get("road_name") or "")
    if "road_pts" in data:
        pts = data["road_pts"]
        if not isinstance(pts, list):
            raise ValueError("Bad road data.")
        fields["road_pts"] = json.dumps(pts)
    return fields


def fields_from_payload(pin_type, data):
    if pin_type == "stay":
        return stay_fields_from_payload(data)
    return business_fields_from_payload(data)


def valid_xy(x, y):
    try:
        x, y = float(x), float(y)
    except (TypeError, ValueError):
        return None
    if -0.05 <= x <= 1.05 and -0.05 <= y <= 1.05:
        return x, y
    return None


# ---------- public pages ----------

@app.route("/")
def index():
    role = compute_role()
    pins, stays = fetch_docs()
    state = {"v": 1, "pins": pins, "stays": stays}
    wx = weather.get_weather()
    return render_template(
        "index.html",
        state_json=json.dumps(state),
        wx_json=json.dumps(wx),
        role_json=json.dumps(role),
    )


@app.route("/redeem")
def redeem_page():
    return render_template("redeem.html")


@app.route("/login")
def login_page():
    return render_template("login.html")


@app.route("/dashboard")
def dashboard_page():
    # The old standalone dashboard is retired -- everything (placing your
    # pin, editing it, photos) now happens right on the themed map.
    return redirect("/")


@app.route("/admin/login")
def admin_login_page():
    return render_template("admin_login.html")


@app.route("/admin")
def admin_page():
    return render_template("admin.html")


@app.route("/static/uploads/<path:name>")
def uploaded_file(name):
    return send_from_directory(UPLOAD_DIR, name)


@app.route("/.well-known/assetlinks.json")
def asset_links():
    """Proves this website and the Android (TWA) app are the same publisher,
    so Chrome hides its address bar inside the app and it feels native. Empty
    until you package the app (e.g. with PWABuilder) -- paste what it gives
    you into well_known/assetlinks.json and redeploy."""
    folder = os.path.join(os.path.dirname(__file__), "well_known")
    path = os.path.join(folder, "assetlinks.json")
    if not os.path.exists(path):
        return jsonify([])
    return send_from_directory(folder, "assetlinks.json")


# ---------- public API ----------

@app.route("/api/pins")
def api_pins():
    pins, stays = fetch_docs()
    return jsonify({"pins": pins, "stays": stays})


@app.route("/api/weather")
def api_weather():
    return jsonify(weather.get_weather())


# ---------- code redemption + owner auth ----------

@app.route("/api/redeem", methods=["POST"])
def api_redeem():
    data = request.get_json(force=True) or {}
    code = (data.get("code") or "").strip().upper()
    email = (data.get("email") or "").strip().lower()
    password = data.get("password") or ""
    if not code or not email or len(password) < 8:
        return jsonify({"error": "Enter your code, an email, and a password (8+ characters)."}), 400

    conn = get_db()
    row = conn.execute("SELECT * FROM invite_codes WHERE code = ?", (code,)).fetchone()
    if not row:
        return jsonify({"error": "That code isn't recognized."}), 404
    if row["status"] != "unused":
        return jsonify({"error": "That code has already been used."}), 409
    if conn.execute("SELECT 1 FROM owners WHERE email = ?", (email,)).fetchone():
        return jsonify({"error": "That email already has an account."}), 409

    pw_hash = auth.hash_password(password)
    cur = conn.execute(
        "INSERT INTO owners (code_id, email, password_hash) VALUES (?, ?, ?)",
        (row["id"], email, pw_hash),
    )
    owner_id = cur.lastrowid
    conn.execute(
        "UPDATE invite_codes SET status = 'claimed', claimed_at = datetime('now') WHERE id = ?",
        (row["id"],),
    )
    conn.commit()

    resp = jsonify({"ok": True, "pin_type": row["pin_type"]})
    token = auth.make_owner_token(owner_id)
    resp.set_cookie("owner_session", token, httponly=True, samesite="Lax", max_age=60 * 60 * 24 * 30)
    return resp


@app.route("/api/login", methods=["POST"])
def api_login():
    data = request.get_json(force=True) or {}
    email = (data.get("email") or "").strip().lower()
    password = data.get("password") or ""
    conn = get_db()
    row = conn.execute("SELECT * FROM owners WHERE email = ?", (email,)).fetchone()
    if not row or not auth.verify_password(password, row["password_hash"]):
        return jsonify({"error": "Wrong email or password."}), 401
    resp = jsonify({"ok": True})
    token = auth.make_owner_token(row["id"])
    resp.set_cookie("owner_session", token, httponly=True, samesite="Lax", max_age=60 * 60 * 24 * 30)
    return resp


@app.route("/api/logout", methods=["POST"])
def api_logout():
    resp = jsonify({"ok": True})
    resp.delete_cookie("owner_session")
    return resp


# ---------- owner: their own pin only ----------

@app.route("/api/my-pin", methods=["GET"])
@owner_required
def api_my_pin_get():
    conn = get_db()
    owner = conn.execute("SELECT o.*, c.pin_type AS code_pin_type FROM owners o "
                          "JOIN invite_codes c ON c.id = o.code_id WHERE o.id = ?",
                          (g.owner_id,)).fetchone()
    pin = conn.execute("SELECT * FROM pins WHERE owner_id = ?", (g.owner_id,)).fetchone()
    doc = None
    if pin:
        _, doc = row_to_client_doc(pin)
    return jsonify({
        "email": owner["email"],
        "allowed_pin_type": owner["code_pin_type"],
        "pin": doc,
    })


@app.route("/api/my-pin", methods=["POST"])
@owner_required
def api_my_pin_create():
    """Place the owner's one and only pin. Fails if they already have one.
    The location is set here and can never be changed again by the owner --
    only an admin edit can move a pin from here on."""
    conn = get_db()
    existing = conn.execute("SELECT 1 FROM pins WHERE owner_id = ?", (g.owner_id,)).fetchone()
    if existing:
        return jsonify({"error": "You've already placed your pin. Edit it instead."}), 409

    owner = conn.execute("SELECT c.pin_type FROM owners o JOIN invite_codes c ON c.id = o.code_id "
                          "WHERE o.id = ?", (g.owner_id,)).fetchone()
    pin_type = owner["pin_type"]
    data = request.get_json(force=True) or {}
    title = (data.get("title") or "").strip()
    xy = valid_xy(data.get("x"), data.get("y"))
    if not title or xy is None:
        return jsonify({"error": "A location on the map and a name are required."}), 400
    x, y = xy

    try:
        fields = fields_from_payload(pin_type, data)
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    fields["title"] = title

    cols = ["owner_id", "pin_type", "x", "y"] + list(fields.keys())
    placeholders = ", ".join("?" for _ in cols)
    values = [g.owner_id, pin_type, x, y] + list(fields.values())
    cur = conn.execute(
        f"INSERT INTO pins ({', '.join(cols)}) VALUES ({placeholders})", values
    )
    conn.commit()
    return jsonify({"ok": True, "id": cur.lastrowid})


@app.route("/api/my-pin", methods=["PUT"])
@owner_required
def api_my_pin_update():
    conn = get_db()
    pin = conn.execute("SELECT * FROM pins WHERE owner_id = ?", (g.owner_id,)).fetchone()
    if not pin:
        return jsonify({"error": "Place your pin first."}), 404
    data = request.get_json(force=True) or {}
    # x, y, and pin_type are never accepted here: an owner can edit their
    # pin's info and photos, but the location is fixed once placed, and only
    # an admin can move it or change what kind of pin it is.
    try:
        fields = fields_from_payload(pin["pin_type"], data)
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    if "title" in data:
        title = (data.get("title") or "").strip()
        if not title:
            return jsonify({"error": "A name is required."}), 400
        fields["title"] = title
    if not fields:
        return jsonify({"error": "Nothing to update."}), 400
    set_clause = ", ".join(f"{k} = ?" for k in fields)
    conn.execute(f"UPDATE pins SET {set_clause}, updated_at = datetime('now') WHERE owner_id = ?",
                 (*fields.values(), g.owner_id))
    conn.commit()
    return jsonify({"ok": True})


def _save_photo(file_storage):
    img = Image.open(file_storage.stream)
    img = ImageOps.exif_transpose(img)  # respect phone camera orientation, then drop the EXIF
    img = img.convert("RGB")
    img.thumbnail((1600, 1600))
    name = f"{uuid.uuid4().hex}.jpg"
    img.save(os.path.join(UPLOAD_DIR, name), "JPEG", quality=82)
    return f"/static/uploads/{name}"


def _add_photo(conn, pin, file):
    photos = json.loads(pin["photos"] or "[]")
    cap = MAX_PHOTOS_BY_TYPE.get(pin["pin_type"], 5)
    if len(photos) >= cap:
        return None, (jsonify({"error": f"Max {cap} photos."}), 400)
    if not file or not file.content_type.startswith("image/"):
        return None, (jsonify({"error": "Please upload an image file."}), 400)
    try:
        path = _save_photo(file)
    except Exception:
        return None, (jsonify({"error": "Couldn't read that image."}), 400)
    photos.append(path)
    conn.execute("UPDATE pins SET photos = ?, updated_at = datetime('now') WHERE id = ?",
                 (json.dumps(photos), pin["id"]))
    conn.commit()
    return photos, None


def _remove_photo(conn, pin, path):
    photos = json.loads(pin["photos"] or "[]")
    if path not in photos:
        return None, (jsonify({"error": "Photo not found."}), 404)
    photos.remove(path)
    conn.execute("UPDATE pins SET photos = ?, updated_at = datetime('now') WHERE id = ?",
                 (json.dumps(photos), pin["id"]))
    conn.commit()
    fname = os.path.basename(path)
    fpath = os.path.join(UPLOAD_DIR, fname)
    if os.path.exists(fpath):
        os.remove(fpath)
    return photos, None


@app.route("/api/my-pin/photos", methods=["POST"])
@owner_required
def api_my_pin_add_photo():
    conn = get_db()
    pin = conn.execute("SELECT * FROM pins WHERE owner_id = ?", (g.owner_id,)).fetchone()
    if not pin:
        return jsonify({"error": "Place your pin first."}), 404
    photos, err = _add_photo(conn, pin, request.files.get("photo"))
    if err:
        return err
    return jsonify({"ok": True, "photos": photos})


@app.route("/api/my-pin/photos", methods=["DELETE"])
@owner_required
def api_my_pin_remove_photo():
    conn = get_db()
    pin = conn.execute("SELECT * FROM pins WHERE owner_id = ?", (g.owner_id,)).fetchone()
    if not pin:
        return jsonify({"error": "Place your pin first."}), 404
    data = request.get_json(force=True) or {}
    photos, err = _remove_photo(conn, pin, data.get("path"))
    if err:
        return err
    return jsonify({"ok": True, "photos": photos})


# ---------- admin ----------

@app.route("/api/admin/login", methods=["POST"])
def api_admin_login():
    data = request.get_json(force=True) or {}
    email = (data.get("email") or "").strip().lower()
    password = data.get("password") or ""
    conn = get_db()
    row = conn.execute("SELECT * FROM admins WHERE email = ?", (email,)).fetchone()
    if not row or not auth.verify_password(password, row["password_hash"]):
        return jsonify({"error": "Wrong email or password."}), 401
    resp = jsonify({"ok": True})
    token = auth.make_admin_token(row["id"])
    resp.set_cookie("admin_session", token, httponly=True, samesite="Lax", max_age=60 * 60 * 24 * 30)
    return resp


@app.route("/api/admin/logout", methods=["POST"])
def api_admin_logout():
    resp = jsonify({"ok": True})
    resp.delete_cookie("admin_session")
    return resp


@app.route("/api/admin/codes", methods=["GET"])
@admin_required
def api_admin_codes_list():
    rows = get_db().execute(
        "SELECT ic.*, o.email AS claimed_by_email FROM invite_codes ic "
        "LEFT JOIN owners o ON o.code_id = ic.id ORDER BY ic.id DESC"
    ).fetchall()
    return jsonify([dict(r) for r in rows])


@app.route("/api/admin/codes", methods=["POST"])
@admin_required
def api_admin_codes_create():
    data = request.get_json(force=True) or {}
    pin_type = data.get("pin_type")
    if pin_type not in ("business", "stay", "custom"):
        return jsonify({"error": "pin_type must be business, stay, or custom."}), 400
    code = auth.gen_invite_code()
    conn = get_db()
    conn.execute("INSERT INTO invite_codes (code, pin_type, label) VALUES (?, ?, ?)",
                 (code, pin_type, data.get("label", "")))
    conn.commit()
    return jsonify({"ok": True, "code": code})


@app.route("/api/admin/codes/<int:code_id>", methods=["DELETE"])
@admin_required
def api_admin_codes_delete(code_id):
    conn = get_db()
    row = conn.execute("SELECT * FROM invite_codes WHERE id = ?", (code_id,)).fetchone()
    if not row:
        return jsonify({"error": "Not found."}), 404
    if row["status"] == "claimed":
        return jsonify({"error": "Can't delete a code that's already been used — delete the owner instead."}), 409
    conn.execute("DELETE FROM invite_codes WHERE id = ?", (code_id,))
    conn.commit()
    return jsonify({"ok": True})


def admin_pin_dict(row):
    d = dict(row)
    d["photos"] = json.loads(d.get("photos") or "[]")
    d["menu"] = json.loads(d.get("menu") or "[]")
    d["availability"] = json.loads(d.get("availability") or "[]")
    d["road_pts"] = json.loads(d.get("road_pts") or "[]")
    return d


@app.route("/api/admin/pins", methods=["GET"])
@admin_required
def api_admin_pins_list():
    rows = get_db().execute(
        "SELECT p.*, o.email AS owner_email FROM pins p LEFT JOIN owners o ON o.id = p.owner_id "
        "ORDER BY p.id"
    ).fetchall()
    return jsonify([admin_pin_dict(r) for r in rows])


@app.route("/api/admin/pins", methods=["POST"])
@admin_required
def api_admin_pins_create():
    """Admin can also drop a pin directly (e.g. a custom landmark, or a
    business/stay with no owner login) anywhere on the map."""
    data = request.get_json(force=True) or {}
    pin_type = data.get("pin_type")
    title = (data.get("title") or "").strip()
    xy = valid_xy(data.get("x"), data.get("y"))
    if pin_type not in ("business", "stay", "custom") or not title or xy is None:
        return jsonify({"error": "pin_type, title, x, and y are required."}), 400
    x, y = xy
    try:
        fields = fields_from_payload(pin_type, data)
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    fields["title"] = title

    cols = ["owner_id", "pin_type", "x", "y"] + list(fields.keys())
    placeholders = ", ".join("?" for _ in cols)
    values = [None, pin_type, x, y] + list(fields.values())
    conn = get_db()
    cur = conn.execute(
        f"INSERT INTO pins ({', '.join(cols)}) VALUES ({placeholders})", values
    )
    conn.commit()
    return jsonify({"ok": True, "id": cur.lastrowid})


@app.route("/api/admin/pins/<int:pin_id>", methods=["PUT"])
@admin_required
def api_admin_pins_update(pin_id):
    conn = get_db()
    pin = conn.execute("SELECT * FROM pins WHERE id = ?", (pin_id,)).fetchone()
    if not pin:
        return jsonify({"error": "Not found."}), 404
    data = request.get_json(force=True) or {}
    try:
        fields = fields_from_payload(pin["pin_type"], data)
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    if "title" in data:
        title = (data.get("title") or "").strip()
        if not title:
            return jsonify({"error": "A name is required."}), 400
        fields["title"] = title
    # The admin -- and only the admin -- can move a pin or replace its photos wholesale.
    if "x" in data or "y" in data:
        xy = valid_xy(data.get("x", pin["x"]), data.get("y", pin["y"]))
        if xy is None:
            return jsonify({"error": "That location is outside the map."}), 400
        fields["x"], fields["y"] = xy
    if "photos" in data:
        photos = data["photos"]
        if not isinstance(photos, list):
            return jsonify({"error": "Bad photo data."}), 400
        fields["photos"] = json.dumps(photos)
    if not fields:
        return jsonify({"error": "Nothing to update."}), 400
    set_clause = ", ".join(f"{k} = ?" for k in fields)
    conn.execute(f"UPDATE pins SET {set_clause}, updated_at = datetime('now') WHERE id = ?",
                 (*fields.values(), pin_id))
    conn.commit()
    return jsonify({"ok": True})


@app.route("/api/admin/pins/<int:pin_id>", methods=["DELETE"])
@admin_required
def api_admin_pins_delete(pin_id):
    conn = get_db()
    conn.execute("DELETE FROM pins WHERE id = ?", (pin_id,))
    conn.commit()
    return jsonify({"ok": True})


@app.route("/api/admin/pins/<int:pin_id>/photos", methods=["POST"])
@admin_required
def api_admin_pin_add_photo(pin_id):
    conn = get_db()
    pin = conn.execute("SELECT * FROM pins WHERE id = ?", (pin_id,)).fetchone()
    if not pin:
        return jsonify({"error": "Not found."}), 404
    photos, err = _add_photo(conn, pin, request.files.get("photo"))
    if err:
        return err
    return jsonify({"ok": True, "photos": photos})


@app.route("/api/admin/pins/<int:pin_id>/photos", methods=["DELETE"])
@admin_required
def api_admin_pin_remove_photo(pin_id):
    conn = get_db()
    pin = conn.execute("SELECT * FROM pins WHERE id = ?", (pin_id,)).fetchone()
    if not pin:
        return jsonify({"error": "Not found."}), 404
    data = request.get_json(force=True) or {}
    photos, err = _remove_photo(conn, pin, data.get("path"))
    if err:
        return err
    return jsonify({"ok": True, "photos": photos})


@app.route("/api/admin/owners/<int:owner_id>", methods=["DELETE"])
@admin_required
def api_admin_owners_delete(owner_id):
    """Fully revoke an owner: deletes their account and pin (FK cascade)."""
    conn = get_db()
    conn.execute("DELETE FROM owners WHERE id = ?", (owner_id,))
    conn.commit()
    return jsonify({"ok": True})


# ---------- ad banner ----------

def ad_to_dict(row):
    return {
        "id": row["id"],
        "image_path": row["image_path"],
        "title": row["title"],
        "link_url": row["link_url"],
        "sort_order": row["sort_order"],
    }


@app.route("/api/ads")
def api_ads():
    """Public: the current ad strip, in display order. Empty list if none set."""
    conn = get_db()
    rows = conn.execute("SELECT * FROM ads ORDER BY sort_order, id").fetchall()
    return jsonify([ad_to_dict(r) for r in rows])


@app.route("/api/admin/ads", methods=["GET"])
@admin_required
def api_admin_ads_list():
    conn = get_db()
    rows = conn.execute("SELECT * FROM ads ORDER BY sort_order, id").fetchall()
    return jsonify([ad_to_dict(r) for r in rows])


@app.route("/api/admin/ads", methods=["POST"])
@admin_required
def api_admin_ads_create():
    file = request.files.get("image")
    if not file or not file.content_type.startswith("image/"):
        return jsonify({"error": "Please upload an image file."}), 400
    title = (request.form.get("title") or "").strip()
    link_url = (request.form.get("link_url") or "").strip()
    try:
        sort_order = int(request.form.get("sort_order") or 0)
    except ValueError:
        sort_order = 0
    try:
        image_path = _save_photo(file)
    except Exception:
        return jsonify({"error": "Couldn't read that image."}), 400
    conn = get_db()
    cur = conn.execute(
        "INSERT INTO ads (image_path, title, link_url, sort_order) VALUES (?, ?, ?, ?)",
        (image_path, title, link_url, sort_order),
    )
    conn.commit()
    row = conn.execute("SELECT * FROM ads WHERE id = ?", (cur.lastrowid,)).fetchone()
    return jsonify({"ok": True, "ad": ad_to_dict(row)})


@app.route("/api/admin/ads/<int:ad_id>", methods=["PUT"])
@admin_required
def api_admin_ads_update(ad_id):
    conn = get_db()
    row = conn.execute("SELECT * FROM ads WHERE id = ?", (ad_id,)).fetchone()
    if not row:
        return jsonify({"error": "Not found."}), 404
    data = request.get_json(force=True) or {}
    title = data.get("title", row["title"])
    link_url = data.get("link_url", row["link_url"])
    try:
        sort_order = int(data.get("sort_order", row["sort_order"]))
    except (TypeError, ValueError):
        sort_order = row["sort_order"]
    conn.execute(
        "UPDATE ads SET title = ?, link_url = ?, sort_order = ? WHERE id = ?",
        (title, link_url, sort_order, ad_id),
    )
    conn.commit()
    return jsonify({"ok": True})


@app.route("/api/admin/ads/<int:ad_id>", methods=["DELETE"])
@admin_required
def api_admin_ads_delete(ad_id):
    conn = get_db()
    row = conn.execute("SELECT * FROM ads WHERE id = ?", (ad_id,)).fetchone()
    if row:
        fpath = os.path.join(UPLOAD_DIR, os.path.basename(row["image_path"]))
        if os.path.exists(fpath):
            os.remove(fpath)
        conn.execute("DELETE FROM ads WHERE id = ?", (ad_id,))
        conn.commit()
    return jsonify({"ok": True})


# ---------- lake chat ----------

CHAT_NAME_MAX = 24
CHAT_MSG_MAX = 500
CHAT_KICK_MINUTES = 5

def chat_cleanup(conn):
    """Lazy expiry: run on every chat request instead of a separate worker.
    Messages vanish 5 hours after posting; a claimed guest name frees up 7
    days after being claimed; an admin kick lifts itself after
    CHAT_KICK_MINUTES unless an admin adds the person back sooner."""
    conn.execute("DELETE FROM chat_messages WHERE created_at < datetime('now', '-5 hours')")
    conn.execute("DELETE FROM chat_names WHERE expires_at < datetime('now')")
    conn.execute("DELETE FROM chat_bans WHERE expires_at IS NOT NULL AND expires_at < datetime('now')")
    conn.execute("DELETE FROM chat_locations WHERE updated_at < datetime('now', '-5 minutes')")
    conn.commit()

def current_chat_sid():
    return request.cookies.get("chat_sid")

def chat_is_banned(conn, session_id, owner_id):
    return chat_ban_row(conn, session_id, owner_id) is not None

def chat_ban_row(conn, session_id, owner_id):
    """The active ban row for this person, if any (None once it has
    expired -- chat_cleanup() deletes expired rows on every request)."""
    if owner_id:
        return conn.execute(
            "SELECT * FROM chat_bans WHERE owner_id = ? ORDER BY id DESC LIMIT 1", (owner_id,)
        ).fetchone()
    if session_id:
        return conn.execute(
            "SELECT * FROM chat_bans WHERE session_id = ? ORDER BY id DESC LIMIT 1", (session_id,)
        ).fetchone()
    return None

def chat_identity(conn):
    """Who is asking: a business/stay owner always chats as their pin's
    title (live, never stored separately); everyone else chats as whatever
    guest name their browser session has claimed, if any."""
    owner_id = current_owner_id()
    if owner_id:
        pin = conn.execute(
            "SELECT title FROM pins WHERE owner_id = ? AND pin_type IN ('business','stay')",
            (owner_id,),
        ).fetchone()
        if pin and (pin["title"] or "").strip():
            name = pin["title"].strip()
            return {"name": name, "name_lower": name.lower(), "session_id": None,
                    "owner_id": owner_id, "kind": "owner",
                    "banned": chat_is_banned(conn, None, owner_id)}
        return None
    sid = current_chat_sid()
    if not sid:
        return None
    row = conn.execute("SELECT * FROM chat_names WHERE session_id = ?", (sid,)).fetchone()
    if not row:
        return None
    return {"name": row["name"], "name_lower": row["name_lower"], "session_id": sid,
            "owner_id": None, "kind": "guest",
            "banned": chat_is_banned(conn, sid, None)}

def _chat_targets(conn):
    """Every name someone could currently be @mentioned by: active guest
    chat names, plus every live business/stay pin title."""
    names = set()
    for row in conn.execute("SELECT name FROM chat_names WHERE expires_at > datetime('now')"):
        names.add(row["name"])
    for row in conn.execute("SELECT title FROM pins WHERE pin_type IN ('business','stay')"):
        if row["title"]:
            names.add(row["title"])
    return names

def _chat_on_lake_names(conn):
    """name_lower of everyone currently reporting themselves as out on the
    lake right now -- guests via their claimed chat_names row, owners via
    their pin. A stale chat_locations row (chat_cleanup) just drops out of
    this join, so nothing needs to actively mark someone as "no longer"."""
    names = set()
    for row in conn.execute(
        "SELECT cn.name_lower FROM chat_locations cl "
        "JOIN chat_names cn ON cn.session_id = cl.session_id "
        "WHERE cl.session_id IS NOT NULL AND cl.on_lake = 1"
    ):
        names.add(row["name_lower"])
    for row in conn.execute(
        "SELECT lower(p.title) AS nl FROM chat_locations cl "
        "JOIN pins p ON p.owner_id = cl.owner_id AND p.pin_type IN ('business','stay') "
        "WHERE cl.owner_id IS NOT NULL AND cl.on_lake = 1"
    ):
        if row["nl"]:
            names.add(row["nl"])
    return names

def _find_mentions(text, targets):
    """Scan text for '@name' where name is a known chat target -- longest
    match first, so a multi-word business name wins over a shorter prefix
    of it, and a match must end at a word boundary."""
    found = set()
    lowered = text.lower()
    candidates = sorted(targets, key=len, reverse=True)
    i, n = 0, len(text)
    while i < n:
        if text[i] == "@":
            rest = lowered[i + 1:]
            for cand in candidates:
                cl = cand.lower()
                if cl and rest.startswith(cl):
                    after = i + 1 + len(cl)
                    nxt = text[after] if after < n else ""
                    if not (nxt.isalnum() or nxt == "_"):
                        found.add(cl)
                        i = after
                        break
            else:
                i += 1
        else:
            i += 1
    return sorted(found)

@app.route("/api/chat/state")
def api_chat_state():
    conn = get_db()
    chat_cleanup(conn)
    identity = chat_identity(conn)
    banned = False
    banned_until = None
    if identity:
        banned = identity["banned"]
    elif not current_owner_id():
        # A kicked guest's claimed name is gone, so chat_identity() can't
        # see them anymore -- check the ban directly by their session so
        # the "removed" screen (and countdown) still shows correctly.
        ban = chat_ban_row(conn, current_chat_sid(), None)
        if ban:
            banned = True
            banned_until = _to_ms(ban["expires_at"]) if ban["expires_at"] else None
    resp = jsonify({
        "name": identity["name"] if identity else None,
        "kind": identity["kind"] if identity else ("owner" if current_owner_id() else "guest"),
        "banned": banned,
        "bannedUntil": banned_until,
        "canClaim": identity is None and not current_owner_id() and not banned,
    })
    if not current_chat_sid() and not current_owner_id():
        resp.set_cookie("chat_sid", uuid.uuid4().hex, httponly=True, samesite="Lax",
                         max_age=60 * 60 * 24 * 400)
    return resp

@app.route("/api/chat/claim", methods=["POST"])
def api_chat_claim():
    if current_owner_id():
        return jsonify({"error": "Your business/stay name is your chat name."}), 400
    conn = get_db()
    chat_cleanup(conn)
    sid = current_chat_sid() or uuid.uuid4().hex
    if chat_is_banned(conn, sid, None):
        return jsonify({"error": "You have been removed from Lake Chat."}), 403
    data = request.get_json(force=True) or {}
    name = (data.get("name") or "").strip()
    if not name or len(name) > CHAT_NAME_MAX:
        return jsonify({"error": f"Pick a name between 1 and {CHAT_NAME_MAX} characters."}), 400
    if not all(c.isalnum() or c in "_- " for c in name):
        return jsonify({"error": "Letters, numbers, spaces, - and _ only."}), 400
    name_lower = name.lower()
    dupe = conn.execute(
        "SELECT 1 FROM chat_names WHERE name_lower = ? AND session_id != ?", (name_lower, sid)
    ).fetchone()
    if dupe:
        return jsonify({"error": "Someone is already using that name today."}), 409
    biz = conn.execute(
        "SELECT 1 FROM pins WHERE pin_type IN ('business','stay') AND lower(title) = ?", (name_lower,)
    ).fetchone()
    if biz:
        return jsonify({"error": "That name belongs to a business/stay on the map."}), 409
    conn.execute("DELETE FROM chat_names WHERE session_id = ?", (sid,))
    conn.execute(
        "INSERT INTO chat_names (name, name_lower, session_id, expires_at) "
        "VALUES (?, ?, ?, datetime('now', '+7 days'))",
        (name, name_lower, sid),
    )
    conn.commit()
    resp = jsonify({"ok": True, "name": name})
    resp.set_cookie("chat_sid", sid, httponly=True, samesite="Lax", max_age=60 * 60 * 24 * 400)
    return resp

@app.route("/api/chat/messages")
def api_chat_messages():
    conn = get_db()
    chat_cleanup(conn)
    rows = conn.execute(
        "SELECT id, name, text, mentions, created_at FROM chat_messages ORDER BY id DESC LIMIT 300"
    ).fetchall()
    messages = [
        {"id": r["id"], "name": r["name"], "text": r["text"],
         "mentions": json.loads(r["mentions"] or "[]"), "at": _to_ms(r["created_at"])}
        for r in reversed(rows)
    ]
    identity = chat_identity(conn)
    you = {"name": identity["name"], "name_lower": identity["name_lower"]} if identity else None
    return jsonify({"messages": messages, "you": you, "onLake": sorted(_chat_on_lake_names(conn))})

@app.route("/api/chat/send", methods=["POST"])
def api_chat_send():
    conn = get_db()
    chat_cleanup(conn)
    identity = chat_identity(conn)
    if not identity:
        return jsonify({"error": "Claim a chat name first."}), 400
    if identity["banned"]:
        return jsonify({"error": "You have been removed from Lake Chat."}), 403
    data = request.get_json(force=True) or {}
    text = (data.get("text") or "").strip()
    if not text:
        return jsonify({"error": "Say something first."}), 400
    text = text[:CHAT_MSG_MAX]
    targets = _chat_targets(conn)
    targets.discard(identity["name"])
    mentions = _find_mentions(text, targets)
    cur = conn.execute(
        "INSERT INTO chat_messages (name, name_lower, session_id, owner_id, text, mentions) "
        "VALUES (?, ?, ?, ?, ?, ?)",
        (identity["name"], identity["name_lower"], identity["session_id"] or "",
         identity["owner_id"], text, json.dumps(mentions)),
    )
    conn.commit()
    row = conn.execute("SELECT id, name, text, mentions, created_at FROM chat_messages WHERE id = ?",
                        (cur.lastrowid,)).fetchone()
    return jsonify({"ok": True, "message": {
        "id": row["id"], "name": row["name"], "text": row["text"],
        "mentions": json.loads(row["mentions"] or "[]"), "at": _to_ms(row["created_at"]),
    }})

@app.route("/api/chat/location", methods=["POST"])
def api_chat_location():
    """A currently-active chatter's device reporting whether it's on the
    lake right now (a yes/no from their own private location marker, never
    their actual coordinates). A no-op if they don't have a chat identity
    yet -- nothing to attach the status to."""
    conn = get_db()
    chat_cleanup(conn)
    identity = chat_identity(conn)
    if not identity:
        return jsonify({"ok": True})
    data = request.get_json(force=True) or {}
    on_lake = 1 if data.get("onLake") else 0
    if identity["owner_id"]:
        conn.execute("DELETE FROM chat_locations WHERE owner_id = ?", (identity["owner_id"],))
        conn.execute(
            "INSERT INTO chat_locations (owner_id, on_lake, updated_at) VALUES (?, ?, datetime('now'))",
            (identity["owner_id"], on_lake),
        )
    else:
        conn.execute("DELETE FROM chat_locations WHERE session_id = ?", (identity["session_id"],))
        conn.execute(
            "INSERT INTO chat_locations (session_id, on_lake, updated_at) VALUES (?, ?, datetime('now'))",
            (identity["session_id"], on_lake),
        )
    conn.commit()
    return jsonify({"ok": True})

@app.route("/api/chat/warnings")
def api_chat_warnings():
    conn = get_db()
    chat_cleanup(conn)
    identity = chat_identity(conn)
    if not identity:
        return jsonify([])
    if identity["owner_id"]:
        rows = conn.execute(
            "SELECT * FROM chat_warnings WHERE owner_id = ? AND read_at IS NULL ORDER BY id",
            (identity["owner_id"],),
        ).fetchall()
    else:
        rows = conn.execute(
            "SELECT * FROM chat_warnings WHERE session_id = ? AND read_at IS NULL ORDER BY id",
            (identity["session_id"],),
        ).fetchall()
    return jsonify([{"id": r["id"], "text": r["text"], "at": _to_ms(r["created_at"])} for r in rows])

@app.route("/api/chat/warnings/<int:warn_id>/ack", methods=["POST"])
def api_chat_warning_ack(warn_id):
    conn = get_db()
    identity = chat_identity(conn)
    if not identity:
        return jsonify({"error": "Not signed in to chat."}), 400
    if identity["owner_id"]:
        conn.execute("UPDATE chat_warnings SET read_at = datetime('now') WHERE id = ? AND owner_id = ?",
                     (warn_id, identity["owner_id"]))
    else:
        conn.execute("UPDATE chat_warnings SET read_at = datetime('now') WHERE id = ? AND session_id = ?",
                     (warn_id, identity["session_id"]))
    conn.commit()
    return jsonify({"ok": True})

# ---------- admin: lake chat moderation ----------

def _chat_resolve_target(conn, name):
    """Find who currently holds this chat name: a guest claim (session_id)
    or a business/stay owner (owner_id). Case-insensitive."""
    name_lower = (name or "").strip().lower()
    row = conn.execute("SELECT session_id FROM chat_names WHERE name_lower = ?", (name_lower,)).fetchone()
    if row:
        return {"session_id": row["session_id"], "owner_id": None, "name_lower": name_lower}
    row = conn.execute(
        "SELECT owner_id FROM pins WHERE pin_type IN ('business','stay') AND lower(title) = ? "
        "AND owner_id IS NOT NULL",
        (name_lower,),
    ).fetchone()
    if row:
        return {"session_id": None, "owner_id": row["owner_id"], "name_lower": name_lower}
    return {"session_id": None, "owner_id": None, "name_lower": name_lower}

@app.route("/api/admin/chat/names")
@admin_required
def api_admin_chat_names():
    conn = get_db()
    chat_cleanup(conn)
    guests = conn.execute(
        "SELECT name, session_id, created_at, expires_at FROM chat_names ORDER BY created_at DESC"
    ).fetchall()
    owners_rows = conn.execute(
        "SELECT p.title AS name, p.owner_id FROM pins p "
        "WHERE p.pin_type IN ('business','stay') AND p.owner_id IS NOT NULL AND p.title != ''"
    ).fetchall()
    out = []
    for r in guests:
        out.append({"name": r["name"], "kind": "guest",
                     "banned": chat_is_banned(conn, r["session_id"], None),
                     "expires_at": r["expires_at"]})
    for r in owners_rows:
        out.append({"name": r["name"], "kind": "owner",
                     "banned": chat_is_banned(conn, None, r["owner_id"]),
                     "expires_at": None})
    return jsonify(out)

@app.route("/api/admin/chat/messages")
@admin_required
def api_admin_chat_messages():
    conn = get_db()
    chat_cleanup(conn)
    rows = conn.execute(
        "SELECT id, name, text, created_at FROM chat_messages ORDER BY id DESC LIMIT 500"
    ).fetchall()
    return jsonify([{"id": r["id"], "name": r["name"], "text": r["text"], "at": _to_ms(r["created_at"])}
                     for r in rows])

@app.route("/api/admin/chat/messages/<int:msg_id>", methods=["DELETE"])
@admin_required
def api_admin_chat_message_delete(msg_id):
    conn = get_db()
    conn.execute("DELETE FROM chat_messages WHERE id = ?", (msg_id,))
    conn.commit()
    return jsonify({"ok": True})

@app.route("/api/admin/chat/messages/by-name", methods=["DELETE"])
@admin_required
def api_admin_chat_messages_by_name():
    data = request.get_json(force=True) or {}
    name_lower = (data.get("name") or "").strip().lower()
    if not name_lower:
        return jsonify({"error": "name required"}), 400
    conn = get_db()
    conn.execute("DELETE FROM chat_messages WHERE name_lower = ?", (name_lower,))
    conn.commit()
    return jsonify({"ok": True})

@app.route("/api/admin/chat/kick", methods=["POST"])
@admin_required
def api_admin_chat_kick():
    data = request.get_json(force=True) or {}
    display_name = (data.get("name") or "").strip()
    conn = get_db()
    target = _chat_resolve_target(conn, display_name)
    if not target["session_id"] and not target["owner_id"]:
        return jsonify({"error": "That name is not currently active in chat."}), 404
    conn.execute(
        "INSERT INTO chat_bans (session_id, owner_id, name, name_lower, expires_at) "
        f"VALUES (?, ?, ?, ?, datetime('now', '+{CHAT_KICK_MINUTES} minutes'))",
        (target["session_id"], target["owner_id"], display_name, target["name_lower"]),
    )
    if target["session_id"]:
        conn.execute("DELETE FROM chat_names WHERE session_id = ?", (target["session_id"],))
    conn.commit()
    return jsonify({"ok": True, "minutes": CHAT_KICK_MINUTES})

@app.route("/api/admin/chat/banned")
@admin_required
def api_admin_chat_banned():
    """Everyone currently kicked, so the admin can add someone back before
    their timeout lifts on its own -- a kicked guest's chat_names row is
    gone, so they would otherwise disappear from the active-names list."""
    conn = get_db()
    chat_cleanup(conn)
    rows = conn.execute(
        "SELECT name, name_lower, owner_id, created_at, expires_at FROM chat_bans ORDER BY created_at DESC"
    ).fetchall()
    return jsonify([
        {
            "name": r["name"] or r["name_lower"],
            "kind": "owner" if r["owner_id"] else "guest",
            "at": _to_ms(r["created_at"]),
            "until": _to_ms(r["expires_at"]) if r["expires_at"] else None,
        }
        for r in rows
    ])

@app.route("/api/admin/chat/unban", methods=["POST"])
@admin_required
def api_admin_chat_unban():
    data = request.get_json(force=True) or {}
    name_lower = (data.get("name") or "").strip().lower()
    conn = get_db()
    conn.execute("DELETE FROM chat_bans WHERE name_lower = ?", (name_lower,))
    conn.commit()
    return jsonify({"ok": True})

@app.route("/api/admin/chat/warn", methods=["POST"])
@admin_required
def api_admin_chat_warn():
    data = request.get_json(force=True) or {}
    text = (data.get("text") or "").strip()
    if not text:
        return jsonify({"error": "Enter a warning message."}), 400
    conn = get_db()
    target = _chat_resolve_target(conn, data.get("name") or "")
    if not target["session_id"] and not target["owner_id"]:
        return jsonify({"error": "That name is not currently active in chat."}), 404
    conn.execute(
        "INSERT INTO chat_warnings (session_id, owner_id, name_lower, text) VALUES (?, ?, ?, ?)",
        (target["session_id"], target["owner_id"], target["name_lower"], text),
    )
    conn.commit()
    return jsonify({"ok": True})


if __name__ == "__main__":
    # Local dev only. In production a WSGI server (gunicorn, per the Procfile)
    # runs `app:app` instead of this block, with debug off.
    port = int(os.environ.get("PORT", 5055))
    debug = os.environ.get("FLASK_DEBUG", "0") == "1"
    app.run(host="0.0.0.0", port=port, debug=debug)
